# Generated by Django 4.0.3 on 2022-03-11 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ehierint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_id', models.IntegerField()),
                ('parent_id', models.IntegerField()),
                ('value', models.IntegerField()),
                ('meaning', models.CharField(max_length=1000)),
                ('selectable', models.IntegerField()),
                ('showcase_order', models.IntegerField()),
                ('encoding_id', models.IntegerField()),
            ],
            options={
                'db_table': 'ehierint',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ehierstring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_id', models.IntegerField()),
                ('parent_id', models.IntegerField()),
                ('value', models.CharField(max_length=1000)),
                ('meaning', models.CharField(max_length=1000)),
                ('selectable', models.IntegerField()),
                ('showcase_order', models.IntegerField()),
                ('encoding_id', models.IntegerField()),
            ],
            options={
                'db_table': 'ehierstring',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Encoding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encoding_id', models.IntegerField()),
                ('title', models.CharField(max_length=1000)),
                ('availability', models.IntegerField()),
                ('coded_as', models.IntegerField()),
                ('structure', models.IntegerField()),
                ('num_members', models.IntegerField()),
                ('descript', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'encoding',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Esimpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DateField()),
                ('meaning', models.CharField(max_length=1000)),
                ('showcase_order', models.IntegerField()),
                ('encoding_id', models.IntegerField()),
            ],
            options={
                'db_table': 'esimpdate',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Esimpint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('meaning', models.CharField(max_length=1000)),
                ('showcase_order', models.IntegerField()),
                ('encoding_id', models.IntegerField()),
            ],
            options={
                'db_table': 'esimpint',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Esimpreal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('meaning', models.CharField(max_length=1000)),
                ('showcase_order', models.IntegerField()),
                ('encoding_id', models.IntegerField()),
            ],
            options={
                'db_table': 'esimpreal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Esimpstring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=1000)),
                ('meaning', models.CharField(max_length=1000)),
                ('showcase_order', models.IntegerField(blank=True, null=True)),
                ('encoding_id', models.IntegerField()),
            ],
            options={
                'db_table': 'esimpstring',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('field_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=1000)),
                ('availability', models.IntegerField()),
                ('stability', models.IntegerField()),
                ('private', models.IntegerField()),
                ('value_type', models.IntegerField()),
                ('base_type', models.IntegerField()),
                ('item_type', models.IntegerField()),
                ('strata', models.IntegerField()),
                ('instanced', models.IntegerField()),
                ('arrayed', models.IntegerField()),
                ('sexed', models.IntegerField()),
                ('units', models.CharField(blank=True, max_length=1000, null=True)),
                ('instance_min', models.IntegerField()),
                ('instance_max', models.IntegerField()),
                ('array_min', models.IntegerField()),
                ('array_max', models.IntegerField()),
                ('notes', models.CharField(blank=True, max_length=1000, null=True)),
                ('debut', models.CharField(max_length=1000)),
                ('version', models.CharField(max_length=1000)),
                ('num_participants', models.IntegerField()),
                ('item_count', models.IntegerField()),
                ('showcase_order', models.IntegerField()),
                ('tier', models.IntegerField()),
                ('instance_id', models.IntegerField()),
                ('encoding_id', models.IntegerField()),
            ],
            options={
                'db_table': 'field',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fieldsum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('item_type', models.IntegerField()),
                ('field_id', models.IntegerField()),
            ],
            options={
                'db_table': 'fieldsum',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Instances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_id', models.IntegerField()),
                ('descript', models.CharField(max_length=1000)),
                ('num_members', models.IntegerField()),
            ],
            options={
                'db_table': 'instances',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Insvalue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('title', models.CharField(max_length=1000)),
                ('descript', models.CharField(max_length=1000)),
                ('instance_id', models.IntegerField()),
            ],
            options={
                'db_table': 'insvalue',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RecordColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=1000)),
                ('column_name', models.CharField(max_length=1000)),
                ('title', models.CharField(max_length=1000)),
                ('value_type', models.IntegerField()),
                ('encoding_id', models.IntegerField()),
                ('orda', models.IntegerField()),
                ('units', models.CharField(blank=True, max_length=1000, null=True)),
                ('notes', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'record_column',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RecordTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=1000)),
                ('parent_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('title', models.CharField(max_length=1000)),
                ('available', models.IntegerField()),
                ('private', models.IntegerField()),
                ('record_field_id', models.IntegerField()),
            ],
            options={
                'db_table': 'record_table',
                'managed': False,
            },
        ),
    ]
