# Generated by Django 4.0.3 on 2022-03-17 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uquery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestDb',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
