# Generated by Django 4.0.3 on 2022-04-14 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uquery', '0002_authgroup_authgrouppermissions_authpermission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataDictionaryShowcase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Path', models.CharField(max_length=1000)),
                ('Category', models.IntegerField()),
                ('FieldID', models.IntegerField()),
                ('Field', models.CharField(max_length=1000)),
                ('Participants', models.IntegerField()),
                ('Items', models.IntegerField()),
                ('Stability', models.CharField(max_length=1000)),
                ('ValueType', models.CharField(max_length=1000)),
                ('Units', models.CharField(max_length=1000)),
                ('ItemType', models.CharField(max_length=1000)),
                ('Strata', models.CharField(max_length=1000)),
                ('Sexed', models.CharField(max_length=1000)),
                ('Instances', models.IntegerField()),
                ('Array', models.IntegerField()),
                ('Coding', models.IntegerField()),
                ('Notes', models.CharField(max_length=1000)),
                ('Link', models.URLField(max_length=1000)),
            ],
        ),
    ]
