# Generated by Django 4.0.3 on 2022-04-14 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uquery', '0003_datadictionaryshowcase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datadictionaryshowcase',
            name='Coding',
            field=models.IntegerField(null=True),
        ),
    ]
