# Generated by Django 4.0.3 on 2022-04-14 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uquery', '0004_alter_datadictionaryshowcase_coding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datadictionaryshowcase',
            name='Link',
        ),
    ]
