# Generated by Django 4.0.3 on 2022-04-14 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uquery', '0005_remove_datadictionaryshowcase_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datadictionaryshowcase',
            name='Notes',
        ),
    ]
