# Generated by Django 4.0.3 on 2022-04-14 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uquery', '0007_remove_datadictionaryshowcase_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datadictionaryshowcase',
            name='Category',
            field=models.IntegerField(null=True),
        ),
    ]
