# Generated by Django 4.0.3 on 2022-04-14 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uquery', '0009_alter_datadictionaryshowcase_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datadictionaryshowcase',
            name='Category',
        ),
    ]
