# Generated by Django 4.0.3 on 2022-04-14 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uquery', '0010_remove_datadictionaryshowcase_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datadictionaryshowcase',
            options={'managed': False},
        ),
    ]
