# Generated by Django 4.0.3 on 2022-04-14 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uquery', '0011_alter_datadictionaryshowcase_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='datadictionaryshowcase',
            table='data_dictionary_showcase',
        ),
    ]
