# Generated by Django 4.0.3 on 2022-04-16 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uquery', '0012_alter_datadictionaryshowcase_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='testJSON',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
